version: '3.8'

services:
  web:
    build: .
    entrypoint: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "7000:7000"
    env_file:
      - .env
    depends_on:
      - redis
      - mysql
    networks:
      - dphish_network

  celery:
    build: .
    command: celery -A project worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - mysql
    networks:
      - dphish_network

  redis:
    image: redis:7.0-alpine
    ports:
      - "6380:6379"
    networks:
      - dphish_network

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: dphish_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dphish_network


volumes:
  mysql_data:

networks:
  dphish_network:
    driver: bridge
